# Day 2 Basic Libraries for Data Science 

## Numpy
### Numpy Basics

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5])

In [3]:
type(array1)

numpy.ndarray

In [4]:
array2 = np.array([1,2,3,4,5])

In [5]:
array2

array([1, 2, 3, 4, 5])

In [6]:
array1

array([1, 2, 3, 4, 5])

In [7]:
array1 + array2

array([ 2,  4,  6,  8, 10])

In [8]:
a = np.array([1,2,3])

b = np.array([ 
                [1,2,3],
                 [4,5,6]
            ])

In [9]:
a + b

array([[2, 4, 6],
       [5, 7, 9]])

In [10]:
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [11]:
b.ndim

2

In [12]:
a.ndim

1

In [13]:
b.shape

(2, 3)

In [14]:
# Need to be explained a.shape

In [15]:
b.size

6

In [16]:
a.size

3

In [17]:
b[  1:, 1: ]

array([[5, 6]])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
c = np.full((3,3), 1)

In [21]:
c.dtype

dtype('int32')

In [22]:
a,b

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [23]:
np.add(a, b)

array([[2, 4, 6],
       [5, 7, 9]])

In [24]:
np.subtract(a,b)

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [25]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [26]:
np.divide(a,b)

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [27]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.arange(1, 10, 5)

array([1, 6])

In [41]:
example_list = []

for i in range(100000):
    example_list.append(i)

In [42]:
numpy_example_list = np.arange(0,100000)

In [43]:
type(numpy_example_list), type(example_list)

(numpy.ndarray, list)

In [32]:
%timeit sum(example_list)

1.92 ms ± 67.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [33]:
# 0.000710 seconds

In [34]:
%timeit np.sum(numpy_example_list)

61 µs ± 496 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [35]:
np.sqrt(25)

5.0

In [36]:
a, b

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [37]:
a < b

array([[False, False, False],
       [ True,  True,  True]])

### Random Number in numpy

In [38]:
np.random.seed(1)
np.random.randint(1,15, size = (5,5))

array([[ 6, 12, 13,  9, 10],
       [12,  6,  1,  1,  2],
       [13,  8, 14, 13,  7],
       [10,  3,  5,  6,  3],
       [ 5, 12, 13, 11, 13]])

In [39]:
np.random.seed(5)
np.random.random(size=(5,5))

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703],
       [0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395]])

### Slicing in numpy n - dim arrays!

In [40]:
ndim_array_example = np.random.randint(1,15, size = (3,3))

In [0]:
ndim_array_example

array([[ 5,  5, 10],
       [ 4, 12,  3],
       [ 5,  7, 10]])

In [0]:
ndim_array_example[ 2:, 1:2 ]

array([[7]])

In [0]:
ndim_array_example[ 2:3, 1: ]

array([[ 7, 10]])

In [0]:
ndim_array_example[1:2, 2:3] + ndim_array_example[1:2, 0:1]

array([[7]])

### Reshaping the Array


In [0]:
a

array([1, 2, 3])

In [0]:
a.shape

(3,)

In [0]:
a = a.reshape((1,3))

In [0]:
a.shape

(1, 3)

In [0]:
a

array([[1, 2, 3]])

In [0]:
a, b

(array([[1, 2, 3]]), array([[1, 2, 3],
        [4, 5, 6]]))

In [0]:
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [0]:
a1 = np.random.randint(1, 3, size = (2,2))

In [0]:
a1

array([[2, 2],
       [1, 2]])

In [0]:
a = 5
b = 6

In [0]:
a, b

(5, 6)

In [0]:
a, b = b, a

In [0]:
a, b

(6, 5)

In [0]:
a1, b1  = np.random.randint(1, 3, size = (2,5)), np.random.randint(1, 3, size = (2,5))

In [0]:
a1, b1

(array([[2, 2, 1, 1, 2],
        [1, 1, 2, 2, 2]]), array([[1, 2, 2, 2, 2],
        [1, 2, 2, 2, 2]]))

In [0]:
a1.dot(b1)

ValueError: ignored

In [0]:
a1.shape

(2, 5)

In [0]:
b1.shape

(2, 5)

In [0]:
a1.dot(b1.reshape((5,2)))

array([[14, 15],
       [15, 14]])

In [0]:
a1.dot(b1.T)

array([[14, 14],
       [15, 15]])

In [0]:
b1.T

array([[1, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

In [0]:
b1.reshape((5,2))

array([[1, 2],
       [2, 2],
       [2, 1],
       [2, 2],
       [2, 2]])

In [0]:
b1

array([[1, 2, 2, 2, 2],
       [1, 2, 2, 2, 2]])

### Sorting an array

In [0]:
a1.sort()

In [0]:
a1

array([[1, 1, 2, 2, 2],
       [1, 1, 2, 2, 2]])

### Data Loading using numpy

In [0]:
data = np.loadtxt("rp.txt", dtype = "str", delimiter=",")